### ISSUE TITLE
Unable to send messages through evalScript() logic

### ISSUE THREAD

**Issue by KevinGrandon** [alinz/react-native-webview-bridge#10]
I am unable to send messages through evaluated scripts, since the latest version has landed. This was working before, but after the update it no longer works. I noticed that eval was changed to evalScript, and I'm wondering if this is still intended to work? My code looks like:

```js
var myPageScripts = function() {
  function WebViewBridgeReady(cb) {
    if (window.WebViewBridge) {
      cb(window.WebViewBridge);
      return;
    }
    function handler() {
      document.removeEventListener('WebViewBridge', handler, false);
      cb(window.WebViewBridge);
    }
    document.addEventListener('WebViewBridge', handler, false);
  }
  WebViewBridgeReady(function (WebViewBridge) {
    WebViewBridge.send("Hello this is me calling from web page");
  });
};

// In react component
componentDidMount() {
  var webviewRef = this.refs.webView;
  var onMessage = function(message) {
    console.log("Received message", message);
  };
  webviewRef.onMessage(onMessage);

  var script = '(' + myPageScripts.toString() + '());';
  webviewRef.evalScript(script);
}
```

@alinz - Any ideas? Thank you!

**Comment by alinz** [comment]
One thing to be aware of, WebView in 0.7.0, 0.7.1 and 0.8 is broken, I have created an issue about it. I thought I did something, but turns out to be something else. Here's the issue https://github.com/facebook/react-native/issues/2010

However, if you target your react-native version to 0.6, you should not have any problem.

About your problem, one thing I notice is that when you load an URL, WebView first goes into `about:black` state and then it goes to URL. There is a hidden method which I haven't expose it yet. I will make it ready by tomorrow since I depend on this library as well. :D

Thanks for testing it.

**Comment by alinz** [comment]
@KevinGrandon I have push a new version plus I added one example which covers your use case. Let me know if you find anything else.

**Comment by KevinGrandon** [comment]
@alinz Thanks! I will test the latest soon. Could you publish version `0.3.1` to npm?

**Comment by KevinGrandon** [comment]
This is great, looks like I just needed to call the `injectBridgeScript` function. Things seem to be working again, and quite well. I think if you just publish 0.3.1 to npm we should be good!

**Comment by alinz** [comment]
It's published in NPM! I will close this ticket. Reopen it if it occurs again.
