### ISSUE TITLE
If url is dynamic the bridge scripts don't get re-injected on url change

### ISSUE THREAD

**Issue by olivierlesnicki** [alinz/react-native-webview-bridge#25]

**Comment by alinz** [comment]
hmm, interesting, let me finds a way to fix this issue. Thanks for reporting this issue.

**Comment by gre** [comment]
Also getting this issue.
I even tried to re-call `bridge.injectBridgeScript();` multiple time after url changes, but the bug still happening.

Wouldn't it possible that the script always is injected (to all pages), without having to imperatively call `bridge.injectBridgeScript();` on user-side ?

**Comment by alinz** [comment]
@gre I will need to look into when I'm fresh, I will debug this during weekend and get back to you ASAP. Thanks for the feedback!

**Comment by gre** [comment]
Hi, actually this seems to work:
```
  onNavigationStateChange(navState) {
    var myWebViewBridgeRef = this.refs.myWebViewBridge;
    var onMessage = function(message) {
      console.log("RECEIVED", message);
    };
    myWebViewBridgeRef.onMessage(onMessage);
    myWebViewBridgeRef.injectBridgeScript();
    myWebViewBridgeRef.evalScript(myPageScripts);
    console.log("CHANGE", navState.url);
  }
```


you can reinject the script everytime the page changes

of course you also need to fix this: https://github.com/alinz/react-native-webview-bridge/issues/40#issuecomment-162530985

**Comment by alinz** [comment]
@gre the new version will automatically inject script if it detects url changes. I think it should fixes your problem as well. Please reopen this issue if you still have the same problem.

**Comment by MacKentoch** [comment]
hi @alinz 

Which version does fix auto re-inject scripts?

I'm trying to implement in ReactNative what I already did with a WKWebview in Swift but no success until now.
Hopefully you gave us all this bridge otherwise I would have to give up.

*I guess I will soon have to learn more about bridging Swift Views with React Native*

**Comment by MacKentoch** [comment]
I remove my previous message.

I use versions `0.16.1` and it works nicely : `scripts keep registered`

My problem came from a need to launch a custom registered javascript in webView on each webView load (for instance after form submit). 

My solution was just a simple add-on (to manage window.onLoad) in injectedScript : 

```javascript 
 // better way than window.onload for load detection and launch custom scripts
 setTimeout(myCustomFunctionToLaunchEachLoad(), 0);
```

**Comment by alinz** [comment]
@MacKentoch what I ended up doing was to react to URL change on WebView. once URL changes, I inject the bridge script. What you can do is register `onLoad` props with WebViewBridge and once that happens you call `myCustomFunctionToLaunchEachLoad`. I hate having `setTimeout` to run my script. It works but it just a hack.

**Comment by MacKentoch** [comment]
@alinz Yes, you are right, it is not the most beautiful way to achieve it.

In fact, first time I used WebView (not talking about WebViewBridge) I had hard time with `onLoad` and `onError` props. It seemed to me like it never fired.
But I surely wrong (*I was unexperienced in that time in react-native*) since I did not have a try then.

I have to speed up and end my application *prototype* then I will take care my `TODO` to get rid of setTimeout as you rightfully suggested.

Thank you for your time and this bridge :+1:
