### ISSUE TITLE
messages containing single quotes can't be sent

### ISSUE THREAD

**Issue by bryanlarsen** [alinz/react-native-webview-bridge#35]
For instance, you can't send "You can't send this".     JSON.stringify'ing it doesn't help, URL encoding or something similar is required to pass single quote marks.

**Comment by alinz** [comment]
@bryanlarsen, I wanted the developer decide how they want to transfer their data. Maybe somebody else wants to send base64 or even binary data. So since both web and React-native are controlled by developer, it would be better to let the developer decide what best for him/her. However if you can find a way to transmit your data, I will be more than happy to help you.

**Comment by bryanlarsen** [comment]
Your code is:

```
NSString *command = [NSString stringWithFormat: @"WebViewBridge.onMessage('%@');", message];
[_webView stringByEvaluatingJavaScriptFromString:command];
```

That puts pretty strong limits on what can be passed through the bridge.   JSON encoding is not good enough.  The documentation should mention that.  I'll open a PR.

**Comment by bryanlarsen** [comment]
AFAICT, there are no good options for an encoding that will pass a single quote.   I was using base64, but that broke as soon as I turned off the chrome debugger: `atob` and `btoa` aren't available in JavascriptCore.  I could pull in a third party module to do encoding, but seems silly.  Instead, I removed the single quotes in WebViewBridge.m#send, and then simply use JSON.stringify in my client code before sending.   That seems like the right solution -- as you said, let the developer decide.   However,  that would break backwards compatibility.

**Comment by alinz** [comment]
@bryanlarsen Your use-case is very specific. Remember, the bridge can only accept string format. You should always use it as a signal rather than sending raw data. It makes your life easier and of course makes the app runs faster. 

Please try to use the new version and let me know if it fixes the problem.

I will keep this issue open for further discussion.

**Comment by alinz** [comment]
Since this is an application related problem, I will close this ticket.

**Comment by bryanlarsen** [comment]
This is not an application error.   Even if react-native-webview-bridge is only designed to pass simple strings, being able to pass single quotes is absolutely required.   There are people with single quotes in their names (O'Leary for example).

Additionally, there is no good built in way to serialize such strings.

- JSON.stringify leaves single quotes untouched
- atob and btoa aren't available in JavascriptCore
- urlencode doesn't work either, I forget why, it's been a while.   it converts a single quote to %27, but there must be some other character tripping it up.

**Comment by alinz** [comment]
@bryanlarsen You can always come up with a new encoding. Such as a simple search and replace. 

`O'Leary => O\/\Leary`

One more thing, You can escape `'` by adding `\` before it. 

```js
var a = 'O\'Leary';
```

this is a valid string and can be parsed. So as I mention this is an application concern not library. 

Thanks

**Comment by gre** [comment]
I agree that the library should fix that, not the user code..
