### ISSUE TITLE
Support file={} option

### ISSUE THREAD

**Issue by EricPKerr** [alinz/react-native-webview-bridge#41]
Similar to https://github.com/alinz/react-native-webview-bridge/issues/38 - It would be nice to link to a local html file instead of pulling in a raw HTML string.

Ideally this would be able to link to other local resources (like additional js/css/images), but those could probably be inlined if necessary.

**Comment by alinz** [comment]
@EricPKerr thank you for your suggestion BUT:

The whole purpose of this module is to extend the WebView to support communication between native js and web js. if you can provide the valid use case I will be happy to think and might start implementing it into this module.

Couple of things to know which preventing me to do this:
- `same origin policy` since you are loading the page from local
- if you can load html to draw something why not just use react-native to implement the whole thing. It runs faster, feels a lot better and you have full control.

Any thoughts?

**Comment by EricPKerr** [comment]
My specific example is embedding the Google Maps JS SDK as there is not yet currently a working react-native Google Maps component.  Enabling this to exist in the webview bridge will allow react-native apps to use these web libraries while their native counterparts are being developed by the community.

**Comment by alinz** [comment]
@EricPKerr I can build the foundation in react-native for google map SDK in iOS. Would you be interested of becoming the contributor for that? I need to maintain every single modules and they take all my time. If you willing to help as a maintainer, I will gladly build one for you.

**Comment by EricPKerr** [comment]
@alinz yeah - that sounds great.  Feel free to email me with specifics on what to do next, it's my github username at gmail.com.

**Comment by alinz** [comment]
@EricPKerr have you seen this [react-native-maps](https://github.com/lelandrichardson/react-native-maps)? Is this going to help you, if so please close this ticket.

**Comment by EricPKerr** [comment]
@alinz looks like a pretty great library. Still unfortunately doesn't use Google Maps for iOS, but i'll probably just roll with this.
