### ISSUE TITLE
Update version to 0.7.0

### ISSUE THREAD

**Issue by KevinGrandon** [alinz/react-native-webview-bridge#9]
Hi @alinz - 

Thank you so much for the recent fixes. Just wanted to say that previously you had published v0.6.0, but then with the latest fixes the version changed to v0.3.0?

It seems like the easiest way to rectify this would be to publish a 0.7.0 version - let me know what you think.

**Comment by KevinGrandon** [comment]
Looks like this happened here: https://github.com/alinz/react-native-webview-bridge/commit/233aa3f9e3db03a11f9ffa959107550fb0bdaf97#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L3

**Comment by alinz** [comment]
At the beginning, I thought if I sync this project's version with react-native's version, that would be a lot easier for everyone to follow up and sync their projects. but so I realize that it's bad idea and since only a few people are using it, I decided to take action and remove version 0.6 and change it to 0.2.2 and release the new version as 0.3.

Another reason is that, I need couple of version numbers before reaching stable 1.0.

What do you think?

**Comment by KevinGrandon** [comment]
Sure, if you've removed 0.6.0, I think that's fine. Although, you basically have infinite version numbers until 1.0. E.g., 0.9.0, 0.10.0, 0.11.0.

Just be careful though, in the future it's always best to increment, it can help the upgrade flow.

**Comment by alinz** [comment]
Thanks for the info. I think I was too tired when I mentioned version number. :( 
Please let me know how the new version works for you.

**Comment by KevinGrandon** [comment]
I am having a few problems. Will file a new issue, and if you could help me I would really appreciate it! Thanks!
