### ISSUE TITLE
android 4.4 ,No response

### ISSUE THREAD

**Issue by robinv8** [alinz/react-native-webview-bridge#91]

**Comment by MacKentoch** [comment]
@tranren @alinz as far as I know (*tested on real devices*) it seems like it works only for `android >= 5.0` (`SDK 21`).

I "guess" (strongly suppose) it is not due to webview bridge but android SDK.
Sorry I can't investigate more since I'm not an android dev.

**So I set my app manifest:**
```xml 
    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="22" />
```

If anyone else could give feedback on android version?
